# rectangle formation yaml
# global goal setting
global_goal:
  # swarm_central_pos: {x: 25.0, y: 0.0, z: 1.0}
  cable_length : 2.0
  m_load : 2.0
  Fcable_1 : {x: 0.0, y: 5.1482, z: 9.8}
  # relative_pos_3 : {x: -1.7321, y: -1.0, z: 0.0} 
  # relative_pos_4 : {x: -1.7321, y: 1.0, z: 0.0}
  # relative_pos_5 : {x: 0.0, y: 2.0, z: 0.0}
  # relative_pos_6 : {x: 1.7321, y: 1.0, z: 0.0} 
  # relative_pos_6 : {x: 0, y: 0, z: 0.0} 

# map_size_x          : 70.0
# map_size_y          : 30.0
# map_size_z          : 3.0
optimization:
  formation_type      : 2
  weight_obstacle     : 100000.0
  weight_swarm        : 50000.0
  weight_feasibility  : 10000.0
  weight_sqrvariance  : 10000.0
  weight_time         : 80.0
  obstacle_clearance  : 1.0
  swarm_clearance     : 0.5
  cable_length        : 2.1213203435596424
  cable_num           : 10
  weight_cable_length : 10000.0
  weight_cable_colli  : 0.0
  cable_tolerance     : 0.05
  load_dist           : 1.0

fsm:
  replan_trajectory_time : 0.1    # s, the max time of replanning trajectory